// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad1.Models.Domian
{
    public partial class Characters
    {
        public long Id { get; set; }
        public long Headgear { get; set; }
        public long Hair { get; set; }
        public long Face { get; set; }
        public long Jacket { get; set; }
        public long Pants { get; set; }
        public long Shoes { get; set; }
        public long Breast { get; set; }
        public long Waist { get; set; }
        public long Skin { get; set; }
        public long Weapon { get; set; }
        public long Job { get; set; }
    }
}