// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Rad2.Models.Domian
{
    public partial class Enrollment
    {
        public enum GradeAssignment
        {
            A, B, C, D, F
        }

        public int EnrollmentId { get; set; }
        public int CourseId { get; set; }
        public int StudentId { get; set; }

//        [DisplayFormat(NullDisplayText = "No grade")]
        public GradeAssignment? Grade { get; set; }

        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}