// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad2.Models.Domian
{
    public partial class Titles
    {
        public Titles()
        {
        }

        public int Id { get; set; }
        public int Id2 { get; set; }
        public string Title { get; set; }
        public int TitleAsc { get; set; }
    }
}
