// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad2.Models.Domian
{
    public partial class CourseAssignment
    {
        public int CourseId { get; set; }
        public int InstructorId { get; set; }

        public virtual Instructor Instructor { get; set; }
        public virtual Course Course { get; set; }
    }
}