// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad4.Models.Domian
{
    public partial class CharacterIds
    {
        public long Id { get; set; }
        public string Cid { get; set; }
        public string Server { get; set; }
    }
}