// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad4.Models.Domian
{
    public partial class Characters
    {
        public int Id { get; set; }
        public int Headgear { get; set; }
        public int Hair { get; set; }
        public int Face { get; set; }
        public int Jacket { get; set; }
        public int Pants { get; set; }
        public int Shoes { get; set; }
        public int Breast { get; set; }
        public int Waist { get; set; }
        public int Skin { get; set; }
        public int Weapon { get; set; }
        public int Job { get; set; }
    }
}