// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad4.Models.Domian
{
    public partial class Person
    {
        public string FirstName { get; set; }
//        public string LastName { get; set; }
    }
}