// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad4.Models.Domian
{
    public partial class T2
    {
        public long Id { get; set; }
        public byte[] Date { get; set; }
        public long? TemperatureC { get; set; }
        public long? TemperatureF { get; set; }
        public string Summary { get; set; }
    }
}