// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad1.Models.Domian
{
    public partial class Items
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long? Part { get; set; }
        public string Desc { get; set; }
    }
}