// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rad1.Models.Domian
{
    public partial class Like
    {
        public long Id { get; set; }
        public long Cid { get; set; }
        public long Uid { get; set; }
        public string CreatedAt { get; set; }
    }
}